trait Layout:
    fn get_size_per_thread(self) -> List[UInt]:
        ...

    fn get_threads_per_warp(self) -> List[UInt]:
        ...

    fn get_warps_per_cta(self) -> List[UInt]:
        ...

    fn get_total_size_per_thread(self, shape: Shape) -> List[UInt]:
        ...
